import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="http://localhost:8090/pingy-chat-widget.js"></script>
      </head>
      <body>{children}
        <script>
          {`PingyChatWidget.init({
            tenantKey: "pingy_14808939E7C0491998CD24268BDE4607",
          });`}
        </script>
      </body>
    </html>
  );
}
